# Image pipline

In [1]:
import pandas as pd

In [2]:
# flake8: noqa

import numpy as np
import pandas as pd
from PIL import Image

from datapipe.datatable import DataStore
from datapipe.store.filedir import PILFile, TableStoreFiledir
from datapipe.store.database import DBConn
from pathlib import Path

In [4]:
from sqlalchemy import create_engine, inspect, text
import sys

sqlite_driver = "sqlite" if sys.platform == "darwin" else "sqlite+pysqlite3"
engine = create_engine(f"{sqlite_driver}:///output/db.sqlite")

inspector = inspect(engine)
table_names = inspector.get_table_names()

print(table_names)

['attr__classification_model__is_best', 'attr__classification_model__is_best_meta', 'attr__detection_model__is_best', 'attr__detection_model__is_best_meta', 'attr__segmentation_model__is_best', 'attr__segmentation_model__is_best_meta', 'best_classification_model', 'best_classification_model_meta', 'best_detection_model', 'best_detection_model_meta', 'best_segmentation_model', 'best_segmentation_model_meta', 'classification_frozen_dataset', 'classification_frozen_dataset__has__image_gt', 'classification_frozen_dataset__has__image_gt_meta', 'classification_frozen_dataset_meta', 'classification_inference_268864e3c5_meta', 'classification_model', 'classification_model__metrics__on__image', 'classification_model__metrics__on__image_meta', 'classification_model__metrics_by_cls_on__subset', 'classification_model__metrics_by_cls_on__subset_meta', 'classification_model__metrics_on__subset', 'classification_model__metrics_on__subset_meta', 'classification_model_is_trained_on_cls_frozen_dataset', 'classification_model_is_trained_on_cls_frozen_dataset_meta', 'classification_model_meta', 'classification_prediction', 'classification_prediction_meta', 'count_classification_metrics_on_image_36dd0438ff_meta', 'count_classification_metrics_on_subset_0056cedd15_meta', 'count_detection_metrics_on_image_c1430334c8_meta', 'count_detection_metrics_on_subset_9645f6d3d6_meta', 'count_pipeline_metrics_on_image_6c4f6c44e8_meta', 'count_pipeline_metrics_on_image_764426b182_meta', 'count_pipeline_metrics_on_image_d1d5a0d3d8_meta', 'count_pipeline_metrics_on_image_d7e4a43874_meta', 'count_pipeline_metrics_on_subset_34f44bbb07_meta', 'count_pipeline_metrics_on_subset_9340c453c4_meta', 'count_pipeline_metrics_on_subset_b1b677b81d_meta', 'count_pipeline_metrics_on_subset_dfc0104035_meta', 'define_ground_truth_for_classification_ce00a4a352_meta', 'detection_frozen_dataset', 'detection_frozen_dataset__class_names', 'detection_frozen_dataset__class_names_meta', 'detection_frozen_dataset__has__image_gt', 'detection_frozen_dataset__has__image_gt_meta', 'detection_frozen_dataset__resized_image_file_meta', 'detection_frozen_dataset__yolo_txt_meta', 'detection_frozen_dataset_meta', 'detection_inference_b1ea4fee39_meta', 'detection_model', 'detection_model__metrics__on__image', 'detection_model__metrics__on__image_meta', 'detection_model__metrics__on__subset', 'detection_model__metrics__on__subset_meta', 'detection_model_is_trained_on_detection_frozen_dataset', 'detection_model_is_trained_on_detection_frozen_dataset_meta', 'detection_model_meta', 'detection_model_thresholds', 'detection_model_thresholds_meta', 'detection_pipeline_model__metrics_by_cls_on__subset', 'detection_pipeline_model__metrics_by_cls_on__subset_meta', 'detection_pipeline_model__metrics_on__image', 'detection_pipeline_model__metrics_on__image_meta', 'detection_pipeline_model__metrics_on__image_with_thrs', 'detection_pipeline_model__metrics_on__image_with_thrs_meta', 'detection_pipeline_model__metrics_on__subset', 'detection_pipeline_model__metrics_on__subset_meta', 'detection_prediction', 'detection_prediction_meta', 'detection_prediction_raw', 'detection_prediction_raw_meta', 'detection_size_for_resize', 'detection_size_for_resize_meta', 'filter_prediction_by_cls_best_thresholds_122d8a1711_meta', 'filter_prediction_by_cls_best_thresholds_4d976dd454_meta', 'get_best_model_4728309f0f_meta', 'get_best_model_9f90d63ccf_meta', 'get_best_model_b48aebdc5c_meta', 'get_best_model_flag_21d15b507a_meta', 'get_best_model_flag_2c8cd05672_meta', 'get_best_model_flag_eafc18497d_meta', 'get_class_names_from_det_frozen_dataset_gt_0a5abbca2d_meta', 'get_class_names_from_det_frozen_dataset_gt_30ac90b36b_meta', 'get_class_names_from_det_frozen_dataset_gt_77aa3852e1_meta', 'get_classes_best_thresholds_1fb43a0d7e_meta', 'get_classes_best_thresholds_a0af3637ab_meta', 'get_size_for_resize_6aa3b513c8_meta', 'get_size_for_resize_71430fbd4d_meta', 'get_size_for_resize_8cec9a010d_meta', 'image', 'image__ground_truth', 'image__ground_truth_for_classification', 'image__ground_truth_for_classification_meta', 'image__ground_truth_meta', 'image_meta', 'resize_and_prepare_yolo_images_0728ddfd0d_meta', 'resize_and_prepare_yolo_images_6a2a493483_meta', 'resize_and_prepare_yolo_images_811c9eeddb_meta', 'sec__detection_model__metrics__on__subset_by_thrs', 'sec__detection_model__metrics__on__subset_by_thrs_meta', 'sec__detection_model__metrics__on__subset_cls_by_thrs', 'sec__detection_model__metrics__on__subset_cls_by_thrs_meta', 'sec__pipeline_segm_metrics_by_cls_with_thrs', 'sec__pipeline_segm_metrics_by_cls_with_thrs_meta', 'sec__pipeline_segm_metrics_on__image_with_thrs', 'sec__pipeline_segm_metrics_on__image_with_thrs_meta', 'sec__pipeline_segm_metrics_with_thrs', 'sec__pipeline_segm_metrics_with_thrs_meta', 'sec__segmentation_prediction_raw', 'sec__segmentation_prediction_raw_meta', 'segm__pipeline_metrics_on__image', 'segm__pipeline_metrics_on__image_meta', 'segm__pipeline_metrics_on_subset', 'segm__pipeline_metrics_on_subset_by_cls', 'segm__pipeline_metrics_on_subset_by_cls_meta', 'segm__pipeline_metrics_on_subset_meta', 'segm_model_is_trained_on_segm_frozen_dataset', 'segm_model_is_trained_on_segm_frozen_dataset_meta', 'segmentation_frozen_dataset', 'segmentation_frozen_dataset__class_names', 'segmentation_frozen_dataset__class_names_meta', 'segmentation_frozen_dataset__coco_txt_meta', 'segmentation_frozen_dataset__has__image_gt', 'segmentation_frozen_dataset__has__image_gt_meta', 'segmentation_frozen_dataset__resized_image_file_meta', 'segmentation_frozen_dataset_meta', 'segmentation_inference_c9933091b1_meta', 'segmentation_model', 'segmentation_model_meta', 'segmentation_model_thresholds', 'segmentation_model_thresholds_meta', 'segmentation_prediction', 'segmentation_prediction_meta', 'segmentation_size_for_resize', 'segmentation_size_for_resize_meta', 'segmentation_yolov8_train_config', 'segmentation_yolov8_train_config_meta', 'subset__has__image', 'subset__has__image_meta', 'tf_classification_train_config', 'tf_classification_train_config_meta', 'train_tf_classification_model_fe5d06aa79_meta', 'train_yolov5_bd2c61c088_meta', 'train_yolov8_5e45f5554e_meta', 'train_yolov8_segmentation_44ddcb45c0_meta', 'yolov5_train_config', 'yolov5_train_config_meta', 'yolov8_det_model_is_trained_on_det_frozen_dataset', 'yolov8_det_model_is_trained_on_det_frozen_dataset_meta', 'yolov8_detection_frozen_dataset__class_names', 'yolov8_detection_frozen_dataset__class_names_meta', 'yolov8_detection_frozen_dataset__resized_image_file_meta', 'yolov8_detection_frozen_dataset__yolo_txt_meta', 'yolov8_detection_size_for_resize', 'yolov8_detection_size_for_resize_meta', 'yolov8_train_config', 'yolov8_train_config_meta']

In [5]:
import pandas as pd

In [8]:
df__image = pd.read_sql_query("SELECT * FROM image", con=engine)

In [9]:
df__image

        image_id                                  image__image_path
0   000000001342  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
1   000000009807  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
2   000000015994  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
3   000000016410  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
4   000000019455  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
5   000000020788  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
6   000000021915  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
7   000000021931  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
8   000000021979  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
9   000000024609  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
10  000000028103  /Users/bobokvsky/datapipe-track/datapipe-ml/te...
11  000000033208  /Users/bobokvsky/datapipe-track/datapipe-ml/te...

In [18]:
import sys
sys.path.append("/home/jovyan/epoch8/ainventory-track/datapipe-ml/tests")
from app import app, ds
from sqlalchemy import text

2025-09-17 15:15:13.385065: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-09-17 15:15:13.404527: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-09-17 15:15:13.411067: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-09-17 15:15:14.911390: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/miniconda3/lib/python3.12/site-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 2.0.8 (you have 1.4.24). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
/usr/miniconda3/lib/python3.12/site-packages/datapipe/store/database.py:65: SAWarning: Dialect sqlite:pysqlite will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  con.execute(text("PRAGMA journal_mode=WAL"))

In [22]:
with ds.meta_dbconn.con.connect() as conn:
    conn.execute(text("DELETE FROM segmentation_frozen_dataset_meta;"))

In [32]:
with ds.meta_dbconn.con.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS segmentation_frozen_dataset__has__image_gt;"))

In [21]:
with ds.meta_dbconn.con.connect() as conn:
    conn.execute(text("DELETE FROM train_tf_classification_model_fe5d06aa79_meta;"))

In [17]:
df = ds.get_table("classification_model").get_data()

In [18]:
df

Empty DataFrame
Columns: [classification_model_id, classification_model__input_size, classification_model__model_path, classification_model__type, classification_model__class_names, classification_model__preprocess_input_script_path]
Index: []

In [9]:
df["classification_model__model_path"] = [df.classification_model__model_path.values[0].replace(".h5", ".keras")]

In [19]:
ds.get_table("classification_model_is_trained_on_cls_frozen_dataset").delete_by_idx(ds.get_table("classification_model_is_trained_on_cls_frozen_dataset").get_data())

In [14]:
df.classification_model__model_path.values

array(['/home/jovyan/epoch8/ainventory-track/datapipe-ml/tests/output/models/20250912_2145_mobilenet96_default/001__train_precision_0.07_train_recall_0.03__val_precision_0.64_val_recall_0.64_val_f1_score_0.02.keras'], dtype=object)

In [15]:
123

123

In [22]:
df = ds.get_table("detection_pipeline_model__metrics_on__image").get_data()
df

,image_id,detection_model_id,subset_id,label,calc__images_support,calc__support,calc__TP,calc__FP,calc__FN,calc__TP_extra_bbox,calc__FP_extra_bbox,calc__FN_extra_bbox
0,000000001342,20250912_1732_yolov5n640_epochs20_default,val,airplane,1,1,0,0,1,0,0,0
1,000000001342,20250912_1732_yolov5n640_epochs20_default,val,baseball bat,0,0,0,1,0,0,0,0
2,000000001342,20250912_1732_yolov5n640_epochs20_default,val,book,1,6,0,0,6,0,0,0
3,000000001342,20250912_1732_yolov5n640_epochs20_default,val,person,1,1,0,0,1,0,0,0
4,000000001342,20250912_1732_yolov5n640_epochs20_default,val,train,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
134,000000479659,20250912_1734_yolo11n640_epochs20_default,val,wine glass,1,2,0,0,2,0,0,0
135,000000522413,20250912_1732_yolov5n640_epochs20_default,val,person,1,1,0,0,1,0,0,0
136,000000522413,20250912_1732_yolov5n640_epochs20_default,val,snowboard,1,1,0,0,1,0,0,0
137,000000522413,20250912_1734_yolo11n640_epochs20_default,val,person,1,1,0,0,1,0,0,0
138,000000522413,20250912_1734_yolo11n640_epochs20_default,val,snowboard,1,1,0,0,1,0,0,0

In [21]:
ds.get_table("detection_pipeline_model__metrics_on__subset").get_data()

,detection_model_id,subset_id,calc__images_support,calc__support,calc__accuracy,calc__weighted_precision,calc__weighted_recall,calc__weighted_f1_score,calc__macro_precision,calc__macro_recall,calc__macro_f1_score,calc__weighted_without_pseudo_classes_precision,calc__weighted_without_pseudo_classes_recall,calc__weighted_without_pseudo_classes_f1_score,calc__macro_without_pseudo_classes_precision,calc__macro_without_pseudo_classes_recall,calc__macro_without_pseudo_classes_f1_score
0,20250912_1732_yolov5n640_epochs20_default,val,20,148,0.124183,0.324003,0.128378,0.183893,0.22619,0.010243,0.513514,0.324003,0.128378,0.183893,0.22619,0.010243,0.513514
1,20250912_1734_yolo11n640_epochs20_default,val,20,148,0.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,NaN

In [6]:
df__image_batches = pd.read_sql_query("SELECT * FROM image_batches", con=engine)

In [7]:
df__image_batches

  image_id task_queue_id  inner_task_id
0       01        queue1              0
1       02        queue1              0
2       03        queue1              1
3       04        queue1              1
4       07        queue2              0
5       08        queue2              0

In [8]:
df__cvat_task = pd.read_sql_query("SELECT * FROM cvat_task", con=engine)
df__cvat_images = pd.read_sql_query("SELECT * FROM cvat_images", con=engine)
df__cvat_task_sync_table = pd.read_sql_query("SELECT * FROM cvat_task_sync_table", con=engine)
df__cvat_annotation = pd.read_sql_query("SELECT * FROM cvat_annotation", con=engine)

In [9]:
df__cvat_task

   project_id task_queue_id  inner_task_id  task_id
0          24        queue1              0      337
1          24        queue1              1      338
2          24        queue2              0      339

In [10]:
df__cvat_task_sync_table

,project_id,task_queue_id,inner_task_id,task_id,cvat_job__status,cvat_job__last_updated
0,24,queue1,0,337,new,2025-08-12 15:25:37.354873
1,24,queue1,1,338,completed,2025-08-12 15:25:51.471319
2,24,queue2,0,339,new,2025-08-12 15:25:59.223049

In [11]:
df__cvat_images

,image_id,task_queue_id,project_id,inner_task_id,task_id,cvat__file_path,inner_frame_id
0,02,queue1,24,0,337,datapipe-cvat-test/02.jpeg,0
1,01,queue1,24,0,337,datapipe-cvat-test/01.jpeg,1
2,03,queue1,24,1,338,datapipe-cvat-test/03.jpeg,0
3,04,queue1,24,1,338,datapipe-cvat-test/04.jpeg,1
4,07,queue2,24,0,339,datapipe-cvat-test/07.jpeg,0
5,08,queue2,24,0,339,datapipe-cvat-test/08.jpeg,1

In [12]:
df__cvat_task_sync_table

,project_id,task_queue_id,inner_task_id,task_id,cvat_job__status,cvat_job__last_updated
0,24,queue1,0,337,new,2025-08-12 15:25:37.354873
1,24,queue1,1,338,completed,2025-08-12 15:25:51.471319
2,24,queue2,0,339,new,2025-08-12 15:25:59.223049

In [13]:
df__cvat_annotation

  image_id task_queue_id                                        annotations
0       03        queue1  <image width="1024" height="1024">\n    <box l...
1       04        queue1  <image width="1024" height="1024">\n    <box l...